# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Gradle@2
  displayName: 'Gradle'
  inputs:
    gradleWrapperFile: '$(Build.SourcesDirectory)/gradlew'
    options: '--no-daemon'
    workingDirectory: '$(Build.SourcesDirectory)'
    tasks: 'buildZip'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'

- task: GitHubRelease@0
  inputs:
    gitHubConnection: 'build'
    repositoryName: '$(Build.Repository.Name)' 
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'auto'
    assets: '$(Build.SourcesDirectory)/build/distributions/tools-1.0-SNAPSHOT.zip'
